Product:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: uid
        AttributeType: S
    KeySchema:
      - AttributeName: uid
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
    TableName: ${file(./env.yml):PRODUCT_TABLE}

ProductStatus:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: uid
        AttributeType: S
    KeySchema:
      - AttributeName: uid
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
    TableName: ${file(./env.yml):PRODUCT_STATUS_TABLE}

ProductComponents:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: uid
        AttributeType: S
    KeySchema:
      - AttributeName: uid
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
    TableName: ${file(./env.yml):PRODUCT_COMPONENTS_TABLE}