service: rdi-test-api
frameworkVersion: '2 || 3'

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    stages:
      - dev
      - development
    seed:
      domain:
        sources:
         - table: ${file(./env.yml):PRODUCT_TABLE}
           sources: [./seed/product.json]
         - table: ${file(./env.yml):PRODUCT_STATUS_TABLE}
           sources: [./seed/product-status.json]
         - table: ${file(./env.yml):PRODUCT_COMPONENTS_TABLE}
           sources: [./seed/product-components.json]

plugins:
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ Products, Arn ]
  environment: ${file(./env.yml)}

functions:
  api:
    handler: ./src/api.handler
    events:
      - httpApi: '*'

resources:
  Resources: ${file(./src/resources.yml)}
